### ISSUE TITLE
Remove TrackIR support?

### ISSUE THREAD

**Issue by ghost** [FirstPersonKSP/KerbTrack#8]
KSP 1.12.5 appears to have built-in TrackIR support (it's in the settings menu, under Control). With this in mind, is there any reason to continue to support TrackIR in this mod?

Arguments for getting rid of it:
- KSP supports TrackIR natively.
- KerbTrack supports OpenTrack, which is an open source (read: better 😉) alternative.
- Dropping of TrackIR support means we can get rid of all the quaternion math, meaning there would only be one path through the code, which should reduce the chance of bugs (of which there are several currently).
- From what I've heard, the TrackIR company has treated open source projects with hostility in the past.
- This mod is many years out of date. Any users still relying on TrackIR support could always stick with an old version, or migrate to KSP's built-in TrackIR support.
- I would like to bring this mod up-to-date, but can't support TrackIR because I don't own one. Do any other mod devs here have one?

**Comment by JonnyOThan** [comment]
I'm pretty new to this whole software ecosystem and I'm still learning how all the pieces fit together.  I'm currently using a webcam, AITrack and OpenTrack, with the TrackIR controller in kerbtrack.  I assume what's happening is OpenTrack is outputting data as if it were TrackIR (the output method is FreeTrack 2.0 enhanced).  The raw opentrack UDP tracker in KerbTrack does work, but it's a far worse experience because there's no mapping curves or filtering.  Maybe there's a way to connect OpenTrack over the udp connection?

OK, yeah if I set OpenTrack to output over UDP then I can use the mapping curves, but it's still far more jittery than using FreeTrack output and TrackIR in KerbTrack.  So I don't think we should remove that option just yet.

**Comment by JonnyOThan** [comment]
OK, the builtin TrackIR support also works OK in flight mode, but is pretty buggy in map mode and IVA mode.  I don't think relying on the builtin support is a good idea.

**Comment by ghost** [comment]
Okay sounds good. I am pretty new to the head track ecosystem too (not to mention C# and Unity).

I just ripped all the TrackIR and FreeTrack stuff out locally (I am doing a cleanup), but I'll have to put it back in.

**Comment by ghost** [comment]
FWIW I am using a smartphone strapped to my head, with the FreePIE android app that's in the OpenTrack repos. It streams over UDP to OpenTrack, which does some filtering and mapping, and then streams over UDP to KerbTrack. It works well, but for some reason there is no translation, only rotation. So I'm not able to test translation right now.

**Comment by ghost** [comment]
Okay, I see what you meant in the first few seconds of this video: https://www.twitch.tv/videos/1510695670, and that is also exactly what I was trying to describe. If I get all the other stuff implemented/fixed, then maybe I'll see about it.
